---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-dashboard-deployment
  namespace: dl
spec:
  selector:
    matchLabels:
      app: storage-dashboard-pods
  replicas: 1
  template:
    metadata:
      labels:
        app: storage-dashboard-pods
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - csc2cxn00000817
      containers:
      - name: storage-dashboard-container
        image: ben4docker/kpadmin:storage-dashboard
        ports:
          - containerPort: 8443
        resources:
          limits:
            memory: "4Gi"
            cpu: "500m"
      imagePullSecrets:
      - name: docker-login
---
apiVersion: v1
kind: Service
metadata:
  name: storage-dashboard-svc
  namespace: dl
spec:
  type: ClusterIP
  ports:
    - targetPort: 8443
      port: 8443
  selector:
    app: storage-dashboard-pods
  externalIPs:
    - 10.15.197.52
---